window.PLANNER_DATA = {
  serviceDate: "",
  jobs: {},
  submittedJobs: [
    {
      id: "survey-merchandiser-20260828-dollar-general-2360",
      provider_id: "survey_merchandiser",
      provider_label: "Survey Merchandiser",
      external_id: "video-20260828-dollar-general-2360",
      title: "Tobacco Products Photo Audit",
      location_name: "Dollar General #2360",
      address: "3926 Lebanon Pike, Hermitage, TN 37076",
      pay_cents: 825,
      due: "Friday, August 28, 2026 6:00 PM",
      distance_miles: 11.4,
      duration_text: "Not visible in screen recording",
      ready_state: "ready_to_start",
      requirements: "Ready to start. Verify full job instructions in Survey Merchandiser before beginning.",
      status: "needs_completion",
      source: "submitted-screen-recording-review",
      source_video: "Screen_Recording_20260828_130331.mp4",
      submitted_at: "2026-08-28T13:03:31",
      order: 1,
    },
    {
      id: "survey-merchandiser-20260828-dollar-general-9802",
      provider_id: "survey_merchandiser",
      provider_label: "Survey Merchandiser",
      external_id: "video-20260828-dollar-general-9802",
      title: "Tobacco Products Photo Audit",
      location_name: "Dollar General #9802",
      address: "5445 Nolensville Rd, Nashville, TN 37211",
      pay_cents: 825,
      due: "Friday, August 28, 2026 6:00 PM",
      distance_miles: 12.3,
      duration_text: "Not visible in screen recording",
      ready_state: "ready_to_start",
      requirements: "Ready to start. Verify full job instructions in Survey Merchandiser before beginning.",
      status: "needs_completion",
      source: "submitted-screen-recording-review",
      source_video: "Screen_Recording_20260828_130331.mp4",
      submitted_at: "2026-08-28T13:03:31",
      order: 2,
    },
    {
      id: "survey-merchandiser-20260828-dollar-general-9822",
      provider_id: "survey_merchandiser",
      provider_label: "Survey Merchandiser",
      external_id: "video-20260828-dollar-general-9822",
      title: "Tobacco Products Photo Audit",
      location_name: "Dollar General #9822",
      address: "4491 Lebanon Pike, Hermitage, TN 37076",
      pay_cents: 825,
      due: "Friday, August 28, 2026 6:00 PM",
      distance_miles: 12.8,
      duration_text: "Not visible in screen recording",
      ready_state: "ready_to_start",
      requirements: "Ready to start. Verify full job instructions in Survey Merchandiser before beginning.",
      status: "needs_completion",
      source: "submitted-screen-recording-review",
      source_video: "Screen_Recording_20260828_130331.mp4",
      submitted_at: "2026-08-28T13:03:31",
      order: 3,
    },
    {
      id: "survey-merchandiser-20260828-dollar-general-1990",
      provider_id: "survey_merchandiser",
      provider_label: "Survey Merchandiser",
      external_id: "video-20260828-dollar-general-1990",
      title: "Tobacco Products Photo Audit",
      location_name: "Dollar General #1990",
      address: "2275 Murfreesboro Pike, Nashville, TN 37217",
      pay_cents: 825,
      due: "Friday, August 28, 2026 6:00 PM",
      distance_miles: 12.8,
      duration_text: "Not visible in screen recording",
      ready_state: "ready_to_start",
      requirements: "Ready to start. Verify full job instructions in Survey Merchandiser before beginning.",
      status: "needs_completion",
      source: "submitted-screen-recording-review",
      source_video: "Screen_Recording_20260828_130331.mp4",
      submitted_at: "2026-08-28T13:03:31",
      order: 4,
    },
    {
      id: "survey-merchandiser-20260828-dollar-general-1901",
      provider_id: "survey_merchandiser",
      provider_label: "Survey Merchandiser",
      external_id: "video-20260828-dollar-general-1901",
      title: "Tobacco Products Photo Audit",
      location_name: "Dollar General #1901",
      address: "13820 Lebanon Rd, Old Hickory, TN 37138",
      pay_cents: 825,
      due: "Friday, August 28, 2026 6:00 PM",
      distance_miles: 15.0,
      duration_text: "Not visible in screen recording",
      ready_state: "ready_to_start",
      requirements: "Ready to start. Verify full job instructions in Survey Merchandiser before beginning.",
      status: "needs_completion",
      source: "submitted-screen-recording-review",
      source_video: "Screen_Recording_20260828_130331.mp4",
      submitted_at: "2026-08-28T13:03:31",
      order: 5,
    },
    {
      id: "survey-merchandiser-20260828-family-dollar-1033",
      provider_id: "survey_merchandiser",
      provider_label: "Survey Merchandiser",
      external_id: "video-20260828-family-dollar-1033",
      title: "Tobacco Products Photo Audit",
      location_name: "Family Dollar #1033",
      address: "1015 Jefferson St, Nashville, TN 37208",
      pay_cents: 650,
      due: "Saturday, August 29, 2026 11:45 PM",
      distance_miles: 3.0,
      duration_text: "Not visible in screen recording",
      ready_state: "ready_to_start",
      requirements: "Ready to start. Verify full job instructions in Survey Merchandiser before beginning.",
      status: "assigned",
      source: "submitted-screen-recording-review",
      source_video: "Screen_Recording_20260828_130331.mp4",
      submitted_at: "2026-08-28T13:03:31",
      order: 6,
    },
    {
      id: "survey-merchandiser-20260828-newroz-market",
      provider_id: "survey_merchandiser",
      provider_label: "Survey Merchandiser",
      external_id: "video-20260828-newroz-market",
      title: "Rice and Flour Product Audit",
      location_name: "Newroz Market",
      address: "393 Elysian Fields Ct, Nashville, TN 37211",
      pay_cents: 1500,
      due: "Sunday, August 30, 2026 11:00 PM",
      distance_miles: 9.7,
      duration_text: "Not visible in screen recording",
      ready_state: "ready_to_start",
      requirements: "Ready to start. Verify full job instructions in Survey Merchandiser before beginning.",
      status: "assigned",
      source: "submitted-screen-recording-review",
      source_video: "Screen_Recording_20260828_130331.mp4",
      submitted_at: "2026-08-28T13:03:31",
      order: 7,
    },
    {
      id: "survey-merchandiser-20260828-patel-brothers",
      provider_id: "survey_merchandiser",
      provider_label: "Survey Merchandiser",
      external_id: "video-20260828-patel-brothers",
      title: "Rice and Flour Product Audit",
      location_name: "Patel Brothers",
      address: "420 Harding Place, Nashville, TN 37211",
      pay_cents: 1500,
      due: "Sunday, August 30, 2026 11:00 PM",
      distance_miles: 10.1,
      duration_text: "Not visible in screen recording",
      ready_state: "ready_to_start",
      requirements: "Ready to start. Verify full job instructions in Survey Merchandiser before beginning.",
      status: "assigned",
      source: "submitted-screen-recording-review",
      source_video: "Screen_Recording_20260828_130331.mp4",
      submitted_at: "2026-08-28T13:03:31",
      order: 8,
    },
    {
      id: "survey-merchandiser-20260828-dollar-general-9805",
      provider_id: "survey_merchandiser",
      provider_label: "Survey Merchandiser",
      external_id: "video-20260828-dollar-general-9805",
      title: "Body Butter Product Audit & Sampling",
      location_name: "Dollar General #9805",
      address: "1945 Madison St, Clarksville, TN 37043",
      pay_cents: 1090,
      due: "Saturday, August 29, 2026 7:30 PM",
      distance_miles: 32.7,
      duration_text: "Not visible in screen recording",
      ready_state: "ready_to_start",
      requirements: "Ready to start. Verify full job instructions in Survey Merchandiser before beginning.",
      status: "assigned",
      source: "submitted-screen-recording-review",
      source_video: "Screen_Recording_20260828_130331.mp4",
      submitted_at: "2026-08-28T13:03:31",
      order: 9,
    },
    {
      id: "survey-merchandiser-20260828-dollar-general-325",
      provider_id: "survey_merchandiser",
      provider_label: "Survey Merchandiser",
      external_id: "video-20260828-dollar-general-325",
      title: "Body Butter Product Audit & Sampling",
      location_name: "Dollar General #325",
      address: "2105 Trenton Rd, Clarksville, TN 37040",
      pay_cents: 1090,
      due: "Saturday, August 29, 2026 7:30 PM",
      distance_miles: 35.5,
      duration_text: "Not visible in screen recording",
      ready_state: "ready_to_start",
      requirements: "Ready to start. Verify full job instructions in Survey Merchandiser before beginning.",
      status: "assigned",
      source: "submitted-screen-recording-review",
      source_video: "Screen_Recording_20260828_130331.mp4",
      submitted_at: "2026-08-28T13:03:31",
      order: 10,
    },
    {
      id: "survey-merchandiser-20260828-dollar-general-6159",
      provider_id: "survey_merchandiser",
      provider_label: "Survey Merchandiser",
      external_id: "video-20260828-dollar-general-6159",
      title: "Body Butter Product Audit & Sampling",
      location_name: "Dollar General #6159",
      address: "3855 Trenton Rd, Clarksville, TN 37040",
      pay_cents: 1090,
      due: "Saturday, August 29, 2026 7:30 PM",
      distance_miles: 38.6,
      duration_text: "Not visible in screen recording",
      ready_state: "ready_to_start",
      requirements: "Ready to start. Verify full job instructions in Survey Merchandiser before beginning.",
      status: "assigned",
      source: "submitted-screen-recording-review",
      source_video: "Screen_Recording_20260828_130331.mp4",
      submitted_at: "2026-08-28T13:03:31",
      order: 11,
    },
    {
      id: "survey-merchandiser-20260828-walmart-3495",
      provider_id: "survey_merchandiser",
      provider_label: "Survey Merchandiser",
      external_id: "video-20260828-walmart-3495",
      title: "Audit and Shelf Dangler Placement at Walmart",
      location_name: "Walmart Supercenter #3495",
      address: "2315 Madison St, Clarksville, TN 37043",
      pay_cents: 1000,
      due: "Not visible in screen recording",
      distance_miles: 31.3,
      duration_text: "Not visible in screen recording",
      ready_state: "awaiting_shipment",
      requirements: "Shipment Required. Do not route until shipment arrives and the job becomes ready.",
      status: "assigned",
      source: "submitted-screen-recording-review",
      source_video: "Screen_Recording_20260828_130331.mp4",
      submitted_at: "2026-08-28T13:03:31",
      order: 12,
    },
    {
      id: "survey-merchandiser-20260828-walmart-673",
      provider_id: "survey_merchandiser",
      provider_label: "Survey Merchandiser",
      external_id: "video-20260828-walmart-673",
      title: "Audit and Shelf Dangler Placement at Walmart",
      location_name: "Walmart #673",
      address: "3050 Wilma Rudolph Blvd, Clarksville, TN 37040",
      pay_cents: 1000,
      due: "Not visible in screen recording",
      distance_miles: 36.3,
      duration_text: "Not visible in screen recording",
      ready_state: "awaiting_shipment",
      requirements: "Shipment Required. Do not route until shipment arrives and the job becomes ready.",
      status: "assigned",
      source: "submitted-screen-recording-review",
      source_video: "Screen_Recording_20260828_130331.mp4",
      submitted_at: "2026-08-28T13:03:31",
      order: 13,
    },
    {
      id: "survey-merchandiser-20260828-walmart-1075",
      provider_id: "survey_merchandiser",
      provider_label: "Survey Merchandiser",
      external_id: "video-20260828-walmart-1075",
      title: "Audit and Shelf Dangler Placement at Walmart",
      location_name: "Walmart #1075",
      address: "1680 Fort Campbell Blvd, Clarksville, TN 37042",
      pay_cents: 1000,
      due: "Not visible in screen recording",
      distance_miles: 40.2,
      duration_text: "Not visible in screen recording",
      ready_state: "awaiting_shipment",
      requirements: "Shipment Required. Do not route until shipment arrives and the job becomes ready.",
      status: "assigned",
      source: "submitted-screen-recording-review",
      source_video: "Screen_Recording_20260828_130331.mp4",
      submitted_at: "2026-08-28T13:03:31",
      order: 14,
    },
    {
      id: "survey-merchandiser-20260828-food-lion-874",
      provider_id: "survey_merchandiser",
      provider_label: "Survey Merchandiser",
      external_id: "video-20260828-food-lion-874",
      title: "Tobacco Inventory Audit & Store System Revision",
      location_name: "Food Lion #874",
      address: "2304 Madison St, Clarksville, TN 37043",
      pay_cents: 1050,
      due: "Starts Thursday, September 10, 2026 7:00 AM",
      distance_miles: 31.2,
      duration_text: "Not visible in screen recording",
      ready_state: "not_ready_to_start",
      requirements: "Upcoming assignment. Not ready to start yet; the app showed a September 10 start window.",
      status: "assigned",
      source: "submitted-screen-recording-review",
      source_video: "Screen_Recording_20260828_130331.mp4",
      submitted_at: "2026-08-28T13:03:31",
      review_note: "OCR showed a conflicting zip code; verify address details before routing.",
      order: 15,
    },
  ],
  sections: {},
  plans: {
    "No posted jobs": [],
  },
  routeColors: {},
  routeIdToShort: {},
};
