buildscript {
    ext {
        compileSdkVersion = 34
        minSdkVersion = 24
        targetSdkVersion = 34
        kotlinVersion = "1.9.24"
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:8.5.2"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

